# **PLC1**

##**Normal Data**

###Load and parse

In [63]:
import pandas as pd

normal_path = "/content/normal_snapshots_PLC1.xlsx"
normal_raw = pd.read_excel(normal_path, header=None)

column_names = [
    "time",
    "current_loop",
    "loop_latency",
    "logic_execution_time",
    "tank_input_valve_status",
    "tank_input_valve_mode",
    "tank_level_value",
    "tank_level_min",
    "tank_level_max",
    "tank_output_valve_status",
    "tank_output_valve_mode",
    "tank_output_flow_value",
]

normal_records = (
    normal_raw.iloc[1:, 0]
    .dropna()
    .astype(str)
    .apply(lambda row: [value.strip() for value in row.split(",")[:12]])
    .tolist()
)

data = pd.DataFrame(normal_records, columns=column_names)
data["time"] = pd.to_datetime(data["time"], errors="coerce")

for column in column_names[1:]:
    data[column] = pd.to_numeric(data[column], errors="coerce")

data = data.sort_values("time").reset_index(drop=True)

print(f"Normal rows: {data.shape[0]} | Normal columns: {data.shape[1]}")
display(data.head())

Normal rows: 81621 | Normal columns: 12

,time,current_loop,loop_latency,logic_execution_time,tank_input_valve_status,tank_input_valve_mode,tank_level_value,tank_level_min,tank_level_max,tank_output_valve_status,tank_output_valve_mode,tank_output_flow_value
0,2025-01-09 22:43:07.335284,1736433786800,14,521,1.0,3.0,5.880000,3.0,7.0,1.0,3.0,0.0000
1,2025-01-09 22:43:07.336299,1736433787400,335,1,1.0,3.0,5.880000,3.0,7.0,1.0,3.0,0.0000
2,2025-01-09 22:43:07.613618,1736433787600,10,3,1.0,3.0,5.886667,3.0,7.0,1.0,3.0,0.0001
3,2025-01-09 22:43:07.822814,1736433787800,3,19,1.0,3.0,5.896667,3.0,7.0,1.0,3.0,0.0001
4,2025-01-09 22:43:08.009138,1736433788000,2,6,1.0,3.0,5.900000,3.0,7.0,1.0,3.0,0.0001

###Validate normal data

In [64]:
print("Missing values:")
display(data.isna().sum())

print("Invalid timestamps:", data["time"].isna().sum())
print("Duplicate timestamps:", data["time"].duplicated().sum())
print("Time is sorted:", data["time"].is_monotonic_increasing)

normal_intervals = data["time"].diff().dt.total_seconds()
print("Time intervals in seconds:")
display(normal_intervals.describe(percentiles=[0.5, 0.95, 0.99]))

Missing values:

time                        0
current_loop                0
loop_latency                0
logic_execution_time        0
tank_input_valve_status     0
tank_input_valve_mode       0
tank_level_value            0
tank_level_min              0
tank_level_max              0
tank_output_valve_status    0
tank_output_valve_mode      0
tank_output_flow_value      0
dtype: int64

Invalid timestamps: 0
Duplicate timestamps: 0
Time is sorted: True
Time intervals in seconds:

count    81620.000000
mean         0.200060
std          0.015628
min          0.000903
50%          0.199952
95%          0.222190
99%          0.227481
max          1.542729
Name: time, dtype: float64

##**Fault Data**

###Load and parse

In [65]:
fault_path = "/content/faults_snapshots_PLC1.xlsx"
fault_raw = pd.read_excel(fault_path, header=None)

fault_records = (
    fault_raw.iloc[1:, 0]
    .dropna()
    .astype(str)
    .apply(lambda row: [value.strip() for value in row.split(",")[:12]])
    .tolist()
)

fault_data = pd.DataFrame(fault_records, columns=column_names)
fault_data["time"] = pd.to_datetime(fault_data["time"], errors="coerce")

for column in column_names[1:]:
    fault_data[column] = pd.to_numeric(fault_data[column], errors="coerce")

fault_data = fault_data.sort_values("time").reset_index(drop=True)

print(f"Fault rows: {fault_data.shape[0]} | Fault columns: {fault_data.shape[1]}")
display(fault_data.head())

Fault rows: 14620 | Fault columns: 12

,time,current_loop,loop_latency,logic_execution_time,tank_input_valve_status,tank_input_valve_mode,tank_level_value,tank_level_min,tank_level_max,tank_output_valve_status,tank_output_valve_mode,tank_output_flow_value
0,2025-01-10 03:22:34.402877,1736450554400,0,1,1.0,3.0,5.820000,3.0,7.0,0.0,3.0,0.0
1,2025-01-10 03:22:34.616614,1736450554600,3,13,1.0,3.0,5.793961,3.0,7.0,0.0,3.0,0.0
2,2025-01-10 03:22:37.146086,1736450554800,2,2343,1.0,3.0,5.960628,3.0,7.0,0.0,3.0,0.0
3,2025-01-10 03:22:37.153484,1736450557200,2147,6,0.0,3.0,5.960628,3.0,7.0,0.0,3.0,0.0
4,2025-01-10 03:22:37.403829,1736450557400,1,1,0.0,3.0,5.960628,3.0,7.0,0.0,3.0,0.0

###Validate fault data

In [66]:
print("Missing values:")
display(fault_data.isna().sum())

print("Invalid timestamps:", fault_data["time"].isna().sum())
print("Duplicate timestamps:", fault_data["time"].duplicated().sum())
print("Time is sorted:", fault_data["time"].is_monotonic_increasing)

fault_intervals = fault_data["time"].diff().dt.total_seconds()
print("Time intervals in seconds:")
display(fault_intervals.describe(percentiles=[0.5, 0.95, 0.99]))

Missing values:

time                        0
current_loop                0
loop_latency                0
logic_execution_time        0
tank_input_valve_status     0
tank_input_valve_mode       0
tank_level_value            0
tank_level_min              0
tank_level_max              0
tank_output_valve_status    0
tank_output_valve_mode      0
tank_output_flow_value      0
dtype: int64

Invalid timestamps: 0
Duplicate timestamps: 0
Time is sorted: True
Time intervals in seconds:

count    14619.000000
mean         0.650311
std          0.938671
min          0.000641
50%          0.205239
95%          2.799696
99%          3.121680
max          3.207293
Name: time, dtype: float64

##**Attack Data**

###Load and parse

In [70]:
import glob
import pandas as pd

attack_files = [
    file for file in glob.glob("/content/attack_snapshots_PLC1*")
    if "Zone.Identifier" not in file
]

print("Matching files:", attack_files)

if not attack_files:
    raise FileNotFoundError("Upload attack_snapshots_PLC1.csv or attack_snapshots_PLC1.xlsx first.")

attack_path = attack_files[0]

if attack_path.lower().endswith(".csv"):
    attack_raw = pd.read_csv(attack_path, header=None, encoding="utf-8-sig")
else:
    attack_raw = pd.read_excel(attack_path, header=None)

column_names = [
    "time",
    "current_loop",
    "loop_latency",
    "logic_execution_time",
    "tank_input_valve_status",
    "tank_input_valve_mode",
    "tank_level_value",
    "tank_level_min",
    "tank_level_max",
    "tank_output_valve_status",
    "tank_output_valve_mode",
    "tank_output_flow_value",
]

packed_rows = (
    attack_raw.shape[1] == 1
    or (attack_raw.shape[1] > 1 and "," in str(attack_raw.iloc[1, 0]))
)

if packed_rows:
    attack_records = (
        attack_raw.iloc[1:, 0]
        .dropna()
        .astype(str)
        .apply(lambda row: [value.strip() for value in row.split(",")[:12]])
        .tolist()
    )
else:
    attack_records = (
        attack_raw.iloc[1:, :12]
        .dropna(how="all")
        .values
        .tolist()
    )

attack_data = pd.DataFrame(attack_records, columns=column_names)
attack_data["time"] = pd.to_datetime(attack_data["time"], errors="coerce")

for column in column_names[1:]:
    attack_data[column] = pd.to_numeric(attack_data[column], errors="coerce")

attack_data = attack_data.sort_values("time").reset_index(drop=True)

print(f"Attack rows: {attack_data.shape[0]} | Attack columns: {attack_data.shape[1]}")
print("Missing values:")
display(attack_data.isna().sum())
display(attack_data.head())

Matching files: ['/content/attack_snapshots_PLC1.xlsx']
Attack rows: 3501 | Attack columns: 12
Missing values:

time                        0
current_loop                0
loop_latency                0
logic_execution_time        0
tank_input_valve_status     0
tank_input_valve_mode       0
tank_level_value            0
tank_level_min              0
tank_level_max              0
tank_output_valve_status    0
tank_output_valve_mode      0
tank_output_flow_value      0
dtype: int64

,time,current_loop,loop_latency,logic_execution_time,tank_input_valve_status,tank_input_valve_mode,tank_level_value,tank_level_min,tank_level_max,tank_output_valve_status,tank_output_valve_mode,tank_output_flow_value
0,2025-02-11 20:27:12.564045,1739276831800,1,744,0.0,3.0,5.820000,3.0,7.0,1.0,3.0,0.0000
1,2025-02-11 20:27:12.587616,1739276832600,567,19,0.0,3.0,5.820000,3.0,7.0,1.0,3.0,0.0000
2,2025-02-11 20:27:12.860225,1739276832800,0,59,0.0,3.0,5.810000,3.0,7.0,1.0,3.0,0.0001
3,2025-02-11 20:27:13.026369,1739276833000,0,26,0.0,3.0,5.803333,3.0,7.0,1.0,3.0,0.0001
4,2025-02-11 20:27:13.225170,1739276833200,1,23,0.0,3.0,5.796667,3.0,7.0,1.0,3.0,0.0001

###Validate attack data

In [71]:
print("Invalid timestamps:", attack_data["time"].isna().sum())
print("Duplicate timestamps:", attack_data["time"].duplicated().sum())
print("Time is sorted:", attack_data["time"].is_monotonic_increasing)

attack_intervals = attack_data["time"].diff().dt.total_seconds()

print("Time intervals in seconds:")
display(attack_intervals.describe(percentiles=[0.5, 0.95, 0.99]))

for column in ["tank_input_valve_status", "tank_output_valve_status"]:
    print(f"{column} values:")
    print(attack_data[column].value_counts(dropna=False).sort_index())

Invalid timestamps: 0
Duplicate timestamps: 0
Time is sorted: True
Time intervals in seconds:

count    3500.000000
mean        0.367018
std         1.106846
min         0.001071
50%         0.201350
95%         1.157692
99%         2.144318
max        37.194649
Name: time, dtype: float64

tank_input_valve_status values:
tank_input_valve_status
0.0    2315
1.0    1186
Name: count, dtype: int64
tank_output_valve_status values:
tank_output_valve_status
0.0    1090
1.0    2411
Name: count, dtype: int64

##**Compare the three datasets**

In [72]:
features = [
    "loop_latency",
    "logic_execution_time",
    "tank_input_valve_status",
    "tank_level_value",
    "tank_output_valve_status",
    "tank_output_flow_value",
]

comparison = pd.concat(
    {
        "normal": data[features].describe().T,
        "fault": fault_data[features].describe().T,
        "attack": attack_data[features].describe().T,
    },
    names=["dataset", "feature"],
)

display(comparison)

                                    count        mean          std       min  \
dataset feature
normal  loop_latency              81621.0    1.944818     6.714863  0.000000
        logic_execution_time      81621.0    9.358535    11.812339  0.000000
        tank_input_valve_status   81621.0    0.359356     0.479815  0.000000
        tank_level_value          81621.0    4.953191     1.415810  0.996667
        tank_output_valve_status  81621.0    0.720917     0.448551  0.000000
        tank_output_flow_value    81621.0    0.000072     0.000045  0.000000
fault   loop_latency              14620.0  451.723529   832.510316  0.000000
        logic_execution_time      14620.0  504.549590   909.749069  0.000000
        tank_input_valve_status   14620.0    0.513748     0.499828  0.000000
        tank_level_value          14620.0    9.779070     0.674227  5.793961
        tank_output_valve_status  14620.0    0.513543     0.499834  0.000000
        tank_output_flow_value    14620.0    0.000051     0.000050  0.000000
attack  loop_latency               3501.0  168.212796  1099.908905  0.000000
        logic_execution_time       3501.0  152.453299  1098.481323  0.000000
        tank_input_valve_status    3501.0    0.338760     0.473356  0.000000
        tank_level_value           3501.0    4.986372     1.311811  2.636667
        tank_output_valve_status   3501.0    0.688660     0.463107  0.000000
        tank_output_flow_value     3501.0    0.000069     0.000046  0.000000

                                        25%        50%         75%         max
dataset feature
normal  loop_latency               0.000000   1.000000    3.000000   1145.0000
        logic_execution_time       3.000000   6.000000   12.000000   1342.0000
        tank_input_valve_status    0.000000   0.000000    1.000000      1.0000
        tank_level_value           3.970000   4.993333    6.000000      8.7900
        tank_output_valve_status   0.000000   1.000000    1.000000      1.0000
        tank_output_flow_value     0.000000   0.000100    0.000100      0.0001
fault   loop_latency               0.000000   2.000000  214.750000   2815.0000
        logic_execution_time       2.000000  10.000000  291.000000   3005.0000
        tank_input_valve_status    0.000000   1.000000    1.000000      1.0000
        tank_level_value           9.903802   9.960457    9.998432     10.0000
        tank_output_valve_status   0.000000   1.000000    1.000000      1.0000
        tank_output_flow_value     0.000000   0.000100    0.000100      0.0001
attack  loop_latency               1.000000   2.000000    4.000000  36872.0000
        logic_execution_time      12.000000  21.000000   26.000000  37157.0000
        tank_input_valve_status    0.000000   0.000000    1.000000      1.0000
        tank_level_value           4.000000   4.863333    6.163333      8.1400
        tank_output_valve_status   0.000000   1.000000    1.000000      1.0000
        tank_output_flow_value     0.000000   0.000100    0.000100      0.0001

##**Check process-variable bounds**

In [73]:
def check_level_bounds(frame, name):
    below_min = frame["tank_level_value"] < frame["tank_level_min"]
    above_max = frame["tank_level_value"] > frame["tank_level_max"]

    print(name)
    print(f"Below minimum: {below_min.sum()} ({below_min.mean():.2%})")
    print(f"Above maximum: {above_max.sum()} ({above_max.mean():.2%})")

check_level_bounds(data, "Normal")
check_level_bounds(fault_data, "Fault")
check_level_bounds(attack_data, "Attack")

Normal
Below minimum: 2402 (2.94%)
Above maximum: 4439 (5.44%)
Fault
Below minimum: 0 (0.00%)
Above maximum: 14171 (96.93%)
Attack
Below minimum: 142 (4.06%)
Above maximum: 262 (7.48%)

##***Final baseline evaluation***

In [76]:
split_index = int(len(data) * 0.70)

normal_train = data.iloc[:split_index].copy()
normal_test = data.iloc[split_index:].copy()

train_timing_thresholds = normal_train[
    ["loop_latency", "logic_execution_time"]
].quantile(0.99)

train_wall_threshold = (
    normal_train["time"]
    .diff()
    .dt.total_seconds()
    .dropna()
    .quantile(0.99)
)

train_loop_threshold = (
    normal_train["current_loop"]
    .diff()
    .dropna()
    .quantile(0.99)
)

def apply_baseline(frame):
    wall_intervals = frame["time"].diff().dt.total_seconds()
    loop_steps = frame["current_loop"].diff()

    return (
        (frame["loop_latency"] > train_timing_thresholds["loop_latency"])
        | (frame["logic_execution_time"] > train_timing_thresholds["logic_execution_time"])
        | (wall_intervals > train_wall_threshold)
        | (loop_steps > train_loop_threshold)
    )

evaluation_sets = {
    "normal_test": normal_test,
    "fault": fault_data,
    "attack": attack_data,
}

evaluation_results = []

for name, frame in evaluation_sets.items():
    flags = apply_baseline(frame)

    evaluation_results.append({
        "dataset": name,
        "flagged_rows": int(flags.sum()),
        "total_rows": len(frame),
        "flagged_rate": flags.mean(),
    })

print("Training timing thresholds:")
display(train_timing_thresholds)

print("Wall interval threshold:", train_wall_threshold)
print("Current loop step threshold:", train_loop_threshold)

display(pd.DataFrame(evaluation_results))

Training timing thresholds:

loop_latency             8.0
logic_execution_time    30.0
Name: 0.99, dtype: float64

Wall interval threshold: 0.22742512
Current loop step threshold: 200.0

       dataset  flagged_rows  total_rows  flagged_rate
0  normal_test           493       24487      0.020133
1        fault          8760       14620      0.599179
2       attack           756        3501      0.215938

#**PLC2**

##**Normal Data**

###Load and parse

In [81]:
import pandas as pd

plc2_columns = [
    "time",
    "current_loop",
    "loop_latency",
    "logic_execution_time",
    "conveyor_belt_engine_status",
    "conveyor_belt_engine_mode",
    "bottle_level_value",
    "bottle_level_max",
    "bottle_distance_to_filler_value",
]

normal_raw = pd.read_excel(
    "/content/normal_snapshots_PLC2.xlsx",
    header=None,
)

normal_records = (
    normal_raw.iloc[1:, 0]
    .dropna()
    .astype(str)
    .apply(lambda row: [value.strip() for value in row.split(",")[:9]])
    .tolist()
)

normal_plc2 = pd.DataFrame(normal_records, columns=plc2_columns)
normal_plc2["time"] = pd.to_datetime(normal_plc2["time"], errors="coerce")

for column in plc2_columns[1:]:
    normal_plc2[column] = pd.to_numeric(normal_plc2[column], errors="coerce")

normal_plc2 = (
    normal_plc2.dropna(subset=["time"])
    .sort_values("time")
    .reset_index(drop=True)
)

print(f"Rows: {normal_plc2.shape[0]} | Columns: {normal_plc2.shape[1]}")
display(normal_plc2.head())

Rows: 81617 | Columns: 9

,time,current_loop,loop_latency,logic_execution_time,conveyor_belt_engine_status,conveyor_belt_engine_mode,bottle_level_value,bottle_level_max,bottle_distance_to_filler_value
0,2025-01-09 22:43:07.612774,1736433787600,9,3,0.0,3.0,0.013333,1.8,0.0
1,2025-01-09 22:43:07.812780,1736433787800,3,9,0.0,3.0,0.053333,1.8,0.0
2,2025-01-09 22:43:08.007705,1736433788000,1,6,0.0,3.0,0.066667,1.8,0.0
3,2025-01-09 22:43:08.206597,1736433788200,1,5,0.0,3.0,0.093333,1.8,0.0
4,2025-01-09 22:43:08.408072,1736433788400,0,8,0.0,3.0,0.120000,1.8,0.0

###Validate normal data

In [82]:
print("Data types:")
print(normal_plc2.dtypes)

print("Missing values:")
display(normal_plc2.isna().sum())

print("Invalid timestamps:", normal_plc2["time"].isna().sum())
print("Duplicate timestamps:", normal_plc2["time"].duplicated().sum())
print("Time is sorted:", normal_plc2["time"].is_monotonic_increasing)

normal_intervals = normal_plc2["time"].diff().dt.total_seconds()
print("Time intervals in seconds:")
display(normal_intervals.describe(percentiles=[0.5, 0.95, 0.99]))

print("Engine status counts:")
print(normal_plc2["conveyor_belt_engine_status"].value_counts().sort_index())

print("Engine mode counts:")
print(normal_plc2["conveyor_belt_engine_mode"].value_counts().sort_index())

print("Bottle level below zero:", (normal_plc2["bottle_level_value"] < 0).sum())
print(
    "Bottle level above maximum:",
    (normal_plc2["bottle_level_value"] > normal_plc2["bottle_level_max"]).sum(),
)

Data types:
time                               datetime64[ns]
current_loop                                int64
loop_latency                                int64
logic_execution_time                        int64
conveyor_belt_engine_status               float64
conveyor_belt_engine_mode                 float64
bottle_level_value                        float64
bottle_level_max                          float64
bottle_distance_to_filler_value           float64
dtype: object
Missing values:

time                               0
current_loop                       0
loop_latency                       0
logic_execution_time               0
conveyor_belt_engine_status        0
conveyor_belt_engine_mode          0
bottle_level_value                 0
bottle_level_max                   0
bottle_distance_to_filler_value    0
dtype: int64

Invalid timestamps: 0
Duplicate timestamps: 0
Time is sorted: True
Time intervals in seconds:

count    81616.000000
mean         0.200066
std          0.016170
min          0.000979
50%          0.199930
95%          0.222918
99%          0.228305
max          1.539170
Name: time, dtype: float64

Engine status counts:
conveyor_belt_engine_status
0.0    61496
1.0    20121
Name: count, dtype: int64
Engine mode counts:
conveyor_belt_engine_mode
2.0    74761
3.0     6856
Name: count, dtype: int64
Bottle level below zero: 0
Bottle level above maximum: 4793

##**Fault Data**

###Load and parse

In [83]:
fault_raw = pd.read_excel(
    "/content/faults_snapshots_PLC2.xlsx",
    header=None,
)

fault_records = (
    fault_raw.iloc[1:, 0]
    .dropna()
    .astype(str)
    .apply(lambda row: [value.strip() for value in row.split(",")[:9]])
    .tolist()
)

fault_plc2 = pd.DataFrame(fault_records, columns=plc2_columns)
fault_plc2["time"] = pd.to_datetime(fault_plc2["time"], errors="coerce")

for column in plc2_columns[1:]:
    fault_plc2[column] = pd.to_numeric(fault_plc2[column], errors="coerce")

fault_plc2 = (
    fault_plc2.dropna(subset=["time"])
    .sort_values("time")
    .reset_index(drop=True)
)

print(f"Rows: {fault_plc2.shape[0]} | Columns: {fault_plc2.shape[1]}")
display(fault_plc2.head())

Rows: 14627 | Columns: 9

,time,current_loop,loop_latency,logic_execution_time,conveyor_belt_engine_status,conveyor_belt_engine_mode,bottle_level_value,bottle_level_max,bottle_distance_to_filler_value
0,2025-01-10 03:22:34.406896,1736450554400,4,2,0.0,3.0,0.0,1.8,0.0
1,2025-01-10 03:22:34.626883,1736450554600,0,27,1.0,3.0,0.0,1.8,0.0
2,2025-01-10 03:22:34.813386,1736450554800,3,1,1.0,3.0,0.0,1.8,19.0
3,2025-01-10 03:22:37.017419,1736450555000,0,2006,1.0,3.0,0.0,1.8,8.0
4,2025-01-10 03:22:37.018419,1736450557000,1818,0,1.0,3.0,0.0,1.8,8.0

###Validate fault data

In [84]:
print("Data types:")
print(fault_plc2.dtypes)

print("Missing values:")
display(fault_plc2.isna().sum())

print("Invalid timestamps:", fault_plc2["time"].isna().sum())
print("Duplicate timestamps:", fault_plc2["time"].duplicated().sum())
print("Time is sorted:", fault_plc2["time"].is_monotonic_increasing)

fault_intervals = fault_plc2["time"].diff().dt.total_seconds()
print("Time intervals in seconds:")
display(fault_intervals.describe(percentiles=[0.5, 0.95, 0.99]))

print("Engine status counts:")
print(fault_plc2["conveyor_belt_engine_status"].value_counts().sort_index())

print("Engine mode counts:")
print(fault_plc2["conveyor_belt_engine_mode"].value_counts().sort_index())

print("Bottle level below zero:", (fault_plc2["bottle_level_value"] < 0).sum())
print(
    "Bottle level above maximum:",
    (fault_plc2["bottle_level_value"] > fault_plc2["bottle_level_max"]).sum(),
)

Data types:
time                               datetime64[ns]
current_loop                                int64
loop_latency                                int64
logic_execution_time                        int64
conveyor_belt_engine_status               float64
conveyor_belt_engine_mode                 float64
bottle_level_value                        float64
bottle_level_max                          float64
bottle_distance_to_filler_value           float64
dtype: object
Missing values:

time                               0
current_loop                       0
loop_latency                       0
logic_execution_time               0
conveyor_belt_engine_status        0
conveyor_belt_engine_mode          0
bottle_level_value                 0
bottle_level_max                   0
bottle_distance_to_filler_value    0
dtype: int64

Invalid timestamps: 0
Duplicate timestamps: 0
Time is sorted: True
Time intervals in seconds:

count    14626.000000
mean         0.649938
std          0.901396
min          0.000766
50%          0.196563
95%          2.213894
99%          2.224276
max          2.263208
Name: time, dtype: float64

Engine status counts:
conveyor_belt_engine_status
0.0        1
1.0    14626
Name: count, dtype: int64
Engine mode counts:
conveyor_belt_engine_mode
1.0    8712
2.0      84
3.0    5831
Name: count, dtype: int64
Bottle level below zero: 0
Bottle level above maximum: 0

##**Attack Data**

###Load and parse

In [85]:
attack_raw = pd.read_excel(
    "/content/attack_snapshots_PLC2.xlsx",
    header=None,
)

attack_records = (
    attack_raw.iloc[1:, 0]
    .dropna()
    .astype(str)
    .apply(lambda row: [value.strip() for value in row.split(",")[:9]])
    .tolist()
)

attack_plc2 = pd.DataFrame(attack_records, columns=plc2_columns)
attack_plc2["time"] = pd.to_datetime(attack_plc2["time"], errors="coerce")

for column in plc2_columns[1:]:
    attack_plc2[column] = pd.to_numeric(attack_plc2[column], errors="coerce")

attack_plc2 = (
    attack_plc2.dropna(subset=["time"])
    .sort_values("time")
    .reset_index(drop=True)
)

print(f"Rows: {attack_plc2.shape[0]} | Columns: {attack_plc2.shape[1]}")
display(attack_plc2.head())

Rows: 4840 | Columns: 9

,time,current_loop,loop_latency,logic_execution_time,conveyor_belt_engine_status,conveyor_belt_engine_mode,bottle_level_value,bottle_level_max,bottle_distance_to_filler_value
0,2025-02-11 20:27:12.663132,1739276832600,0,62,0.0,3.0,0.000000,1.8,0.0
1,2025-02-11 20:27:12.859725,1739276832800,1,58,0.0,3.0,0.026667,1.8,0.0
2,2025-02-11 20:27:13.024270,1739276833000,1,23,0.0,3.0,0.053333,1.8,0.0
3,2025-02-11 20:27:13.226307,1739276833200,1,25,0.0,3.0,0.080000,1.8,0.0
4,2025-02-11 20:27:13.424185,1739276833400,0,24,0.0,3.0,0.106667,1.8,0.0

###Validate fault data

In [86]:
print("Data types:")
print(attack_plc2.dtypes)

print("Missing values:")
display(attack_plc2.isna().sum())

print("Invalid timestamps:", attack_plc2["time"].isna().sum())
print("Duplicate timestamps:", attack_plc2["time"].duplicated().sum())
print("Time is sorted:", attack_plc2["time"].is_monotonic_increasing)

attack_intervals = attack_plc2["time"].diff().dt.total_seconds()
print("Time intervals in seconds:")
display(attack_intervals.describe(percentiles=[0.5, 0.95, 0.99]))

print("Engine status counts:")
print(attack_plc2["conveyor_belt_engine_status"].value_counts().sort_index())

print("Engine mode counts:")
print(attack_plc2["conveyor_belt_engine_mode"].value_counts().sort_index())

print("Bottle level below zero:", (attack_plc2["bottle_level_value"] < 0).sum())
print(
    "Bottle level above maximum:",
    (attack_plc2["bottle_level_value"] > attack_plc2["bottle_level_max"]).sum(),
)

Data types:
time                               datetime64[ns]
current_loop                                int64
loop_latency                                int64
logic_execution_time                        int64
conveyor_belt_engine_status               float64
conveyor_belt_engine_mode                 float64
bottle_level_value                        float64
bottle_level_max                          float64
bottle_distance_to_filler_value           float64
dtype: object
Missing values:

time                               0
current_loop                       0
loop_latency                       0
logic_execution_time               0
conveyor_belt_engine_status        0
conveyor_belt_engine_mode          0
bottle_level_value                 0
bottle_level_max                   0
bottle_distance_to_filler_value    0
dtype: int64

Invalid timestamps: 0
Duplicate timestamps: 0
Time is sorted: True
Time intervals in seconds:

count    4839.000000
mean        0.265595
std         0.726130
min         0.001847
50%         0.201198
95%         0.437214
99%         1.172284
max        30.142357
Name: time, dtype: float64

Engine status counts:
conveyor_belt_engine_status
0.0    3683
1.0    1157
Name: count, dtype: int64
Engine mode counts:
conveyor_belt_engine_mode
3.0    4840
Name: count, dtype: int64
Bottle level below zero: 0
Bottle level above maximum: 389

##**Compare the three datasets**

In [87]:
plc2_datasets = {
    "normal": normal_plc2,
    "fault": fault_plc2,
    "attack": attack_plc2,
}

plc2_features = [
    "loop_latency",
    "logic_execution_time",
    "conveyor_belt_engine_status",
    "conveyor_belt_engine_mode",
    "bottle_level_value",
    "bottle_distance_to_filler_value",
]

plc2_comparison = pd.concat(
    {
        name: frame[plc2_features].describe().T
        for name, frame in plc2_datasets.items()
    },
    names=["dataset", "feature"],
)

display(plc2_comparison)

for name, frame in plc2_datasets.items():
    print(f"\n{name} engine status:")
    print(frame["conveyor_belt_engine_status"].value_counts().sort_index())

    print(f"\n{name} engine mode:")
    print(frame["conveyor_belt_engine_mode"].value_counts().sort_index())

    above_max = frame["bottle_level_value"] > frame["bottle_level_max"]
    print(f"\n{name} bottle level above maximum: {above_max.sum()} ({above_max.mean():.2%})")

                                           count        mean         std  min  \
dataset feature
normal  loop_latency                     81617.0    2.087715    6.738064  0.0
        logic_execution_time             81617.0    8.690334   11.382311  0.0
        conveyor_belt_engine_status      81617.0    0.246530    0.430993  0.0
        conveyor_belt_engine_mode        81617.0    2.084002    0.277393  2.0
        bottle_level_value               81617.0    0.631134    0.566516  0.0
        bottle_distance_to_filler_value  81617.0    2.916972    4.848724  0.0
fault   loop_latency                     14627.0  455.316538  786.169788  0.0
        logic_execution_time             14627.0  504.206467  866.328771  0.0
        conveyor_belt_engine_status      14627.0    0.999932    0.008268  0.0
        conveyor_belt_engine_mode        14627.0    1.803035    0.977511  1.0
        bottle_level_value               14627.0    0.000864    0.004929  0.0
        bottle_distance_to_filler_value  14627.0    9.670643    5.779520  0.0
attack  loop_latency                      4840.0   67.451446  718.912840  0.0
        logic_execution_time              4840.0  112.521901  731.465148  1.0
        conveyor_belt_engine_status       4840.0    0.239050    0.426547  0.0
        conveyor_belt_engine_mode         4840.0    3.000000    0.000000  3.0
        bottle_level_value                4840.0    0.628044    0.608242  0.0
        bottle_distance_to_filler_value   4840.0    2.830062    4.783761  0.0

                                               25%        50%        75%  \
dataset feature
normal  loop_latency                      1.000000   2.000000   3.000000
        logic_execution_time              3.000000   5.000000  11.000000
        conveyor_belt_engine_status       0.000000   0.000000   0.000000
        conveyor_belt_engine_mode         2.000000   2.000000   2.000000
        bottle_level_value                0.013333   0.546667   1.093333
        bottle_distance_to_filler_value   0.500000   1.000000   1.000000
fault   loop_latency                      0.000000   2.000000  15.000000
        logic_execution_time              1.000000   3.000000  42.000000
        conveyor_belt_engine_status       1.000000   1.000000   1.000000
        conveyor_belt_engine_mode         1.000000   1.000000   3.000000
        bottle_level_value                0.000000   0.000000   0.000000
        bottle_distance_to_filler_value   4.750000  10.000000  15.000000
attack  loop_latency                      0.000000   1.000000   3.000000
        logic_execution_time             13.000000  23.000000  56.000000
        conveyor_belt_engine_status       0.000000   0.000000   0.000000
        conveyor_belt_engine_mode         3.000000   3.000000   3.000000
        bottle_level_value                0.000000   0.493333   1.123333
        bottle_distance_to_filler_value   0.500000   1.000000   1.000000

                                                  max
dataset feature
normal  loop_latency                      1142.000000
        logic_execution_time              1342.000000
        conveyor_belt_engine_status          1.000000
        conveyor_belt_engine_mode            3.000000
        bottle_level_value                   1.973333
        bottle_distance_to_filler_value     19.500000
fault   loop_latency                      1865.000000
        logic_execution_time              2037.000000
        conveyor_belt_engine_status          1.000000
        conveyor_belt_engine_mode            3.000000
        bottle_level_value                   0.040000
        bottle_distance_to_filler_value     19.500000
attack  loop_latency                     29853.000000
        logic_execution_time             30046.000000
        conveyor_belt_engine_status          1.000000
        conveyor_belt_engine_mode            3.000000
        bottle_level_value                   2.000000
        bottle_distance_to_filler_value     19.500000

normal engine status:
conveyor_belt_engine_status
0.0    61496
1.0    20121
Name: count, dtype: int64

normal engine mode:
conveyor_belt_engine_mode
2.0    74761
3.0     6856
Name: count, dtype: int64

normal bottle level above maximum: 4793 (5.87%)

fault engine status:
conveyor_belt_engine_status
0.0        1
1.0    14626
Name: count, dtype: int64

fault engine mode:
conveyor_belt_engine_mode
1.0    8712
2.0      84
3.0    5831
Name: count, dtype: int64

fault bottle level above maximum: 0 (0.00%)

attack engine status:
conveyor_belt_engine_status
0.0    3683
1.0    1157
Name: count, dtype: int64

attack engine mode:
conveyor_belt_engine_mode
3.0    4840
Name: count, dtype: int64

attack bottle level above maximum: 389 (8.04%)

##**Check process-variable**

In [88]:
for name, frame in {
    "Normal": normal_plc2,
    "Fault": fault_plc2,
    "Attack": attack_plc2,
}.items():
    above_max = frame["bottle_level_value"] > frame["bottle_level_max"]

    print(f"{name}")
    print(f"Above maximum: {above_max.sum()} ({above_max.mean():.2%})")

Normal
Above maximum: 4793 (5.87%)
Fault
Above maximum: 0 (0.00%)
Attack
Above maximum: 389 (8.04%)

##***Final baseline evaluation***

In [89]:
split_index = int(len(normal_plc2) * 0.70)
normal_train_plc2 = normal_plc2.iloc[:split_index].copy()
normal_test_plc2 = normal_plc2.iloc[split_index:].copy()

timing_columns = ["loop_latency", "logic_execution_time"]
timing_thresholds = normal_train_plc2[timing_columns].quantile(0.99)

wall_threshold = (
    normal_train_plc2["time"]
    .diff()
    .dt.total_seconds()
    .dropna()
    .quantile(0.99)
)

loop_step_threshold = (
    normal_train_plc2["current_loop"]
    .diff()
    .dropna()
    .quantile(0.99)
)

def apply_baseline(frame):
    wall_intervals = frame["time"].diff().dt.total_seconds()
    loop_steps = frame["current_loop"].diff()

    return (
        (frame["loop_latency"] > timing_thresholds["loop_latency"])
        | (frame["logic_execution_time"] > timing_thresholds["logic_execution_time"])
        | (wall_intervals > wall_threshold)
        | (loop_steps > loop_step_threshold)
    )

evaluation_sets = {
    "normal_test": normal_test_plc2,
    "fault": fault_plc2,
    "attack": attack_plc2,
}

results = []

for name, frame in evaluation_sets.items():
    flags = apply_baseline(frame)
    results.append({
        "dataset": name,
        "flagged_rows": int(flags.sum()),
        "total_rows": len(frame),
        "flagged_rate": flags.mean(),
    })

print("Training timing thresholds:")
display(timing_thresholds)
print("Wall interval threshold:", wall_threshold)
print("Current loop step threshold:", loop_step_threshold)
display(pd.DataFrame(results))

Training timing thresholds:

loop_latency             8.0
logic_execution_time    29.0
Name: 0.99, dtype: float64

Wall interval threshold: 0.22834384
Current loop step threshold: 200.0

       dataset  flagged_rows  total_rows  flagged_rate
0  normal_test           552       24486      0.022543
1        fault          7423       14627      0.507486
2       attack          1598        4840      0.330165

#**Combined PLC1 and PLC2 baseline**

In [92]:
normal_datasets = {
    "PLC1": data,
    "PLC2": normal_plc2,
}

train_sets = {}
test_sets = {}

for plc_name, frame in normal_datasets.items():
    split_index = int(len(frame) * 0.70)
    train_sets[plc_name] = frame.iloc[:split_index].copy()
    test_sets[plc_name] = frame.iloc[split_index:].copy()

combined_train = pd.concat(train_sets.values(), ignore_index=True)

timing_columns = ["loop_latency", "logic_execution_time"]
timing_thresholds = combined_train[timing_columns].quantile(0.99)

wall_intervals = pd.concat([
    frame["time"].diff().dt.total_seconds().dropna()
    for frame in train_sets.values()
], ignore_index=True)

loop_steps = pd.concat([
    frame["current_loop"].diff().dropna()
    for frame in train_sets.values()
], ignore_index=True)

wall_threshold = wall_intervals.quantile(0.99)
loop_step_threshold = loop_steps.quantile(0.99)

def apply_combined_baseline(frame):
    wall_gaps = frame["time"].diff().dt.total_seconds()
    loop_jumps = frame["current_loop"].diff()

    return (
        (frame["loop_latency"] > timing_thresholds["loop_latency"])
        | (frame["logic_execution_time"] > timing_thresholds["logic_execution_time"])
        | (wall_gaps > wall_threshold)
        | (loop_jumps > loop_step_threshold)
    )

evaluation_sets = {
    "normal_test_PLC1": test_sets["PLC1"],
    "normal_test_PLC2": test_sets["PLC2"],
    "fault_PLC1": fault_data,
    "fault_PLC2": fault_plc2,
    "attack_PLC1": attack_data,
    "attack_PLC2": attack_plc2,
}

results = []

for name, frame in evaluation_sets.items():
    flags = apply_combined_baseline(frame)

    results.append({
        "dataset": name,
        "flagged_rows": int(flags.sum()),
        "total_rows": len(frame),
        "flagged_rate": flags.mean(),
    })

results_table = pd.DataFrame(results)

print("Combined training timing thresholds:")
display(timing_thresholds)
print("Combined wall interval threshold:", wall_threshold)
print("Combined current loop step threshold:", loop_step_threshold)

display(results_table)

Combined training timing thresholds:

loop_latency             8.0
logic_execution_time    29.0
Name: 0.99, dtype: float64

Combined wall interval threshold: 0.22788638
Combined current loop step threshold: 200.0

            dataset  flagged_rows  total_rows  flagged_rate
0  normal_test_PLC1           534       24487      0.021807
1  normal_test_PLC2           593       24486      0.024218
2        fault_PLC1          8749       14620      0.598427
3        fault_PLC2          7425       14627      0.507623
4       attack_PLC1           767        3501      0.219080
5       attack_PLC2          1598        4840      0.330165

In [93]:
summary = results_table.copy()

summary["category"] = (
    summary["dataset"]
    .str.rsplit("_", n=1)
    .str[0]
    .replace({"normal_test": "normal"})
)

combined_summary = (
    summary.groupby("category", as_index=False)
    .agg(
        flagged_rows=("flagged_rows", "sum"),
        total_rows=("total_rows", "sum"),
    )
)

combined_summary["flagged_rate"] = (
    combined_summary["flagged_rows"] / combined_summary["total_rows"]
)

display(combined_summary)

  category  flagged_rows  total_rows  flagged_rate
0   attack          2365        8341      0.283539
1    fault         16174       29247      0.553014
2   normal          1127       48973      0.023013

#**Models**

In [94]:
def build_model_data(normal_frame, fault_frame, attack_frame, plc_name):
    parts = []

    for label, frame in [
        ("normal", normal_frame),
        ("fault", fault_frame),
        ("attack", attack_frame),
    ]:
        part = frame.copy()
        part["wall_interval_seconds"] = part["time"].diff().dt.total_seconds()
        part["current_loop_delta"] = part["current_loop"].diff()
        part["label"] = label
        part["plc"] = plc_name
        parts.append(part)

    return (
        pd.concat(parts, ignore_index=True)
        .dropna(subset=["wall_interval_seconds", "current_loop_delta"])
        .reset_index(drop=True)
    )

plc1_model_data = build_model_data(
    data,
    fault_data,
    attack_data,
    "PLC1",
)

plc2_model_data = build_model_data(
    normal_plc2,
    fault_plc2,
    attack_plc2,
    "PLC2",
)

print("PLC1 rows by class:")
print(plc1_model_data["label"].value_counts())

print("\nPLC2 rows by class:")
print(plc2_model_data["label"].value_counts())

PLC1 rows by class:
label
normal    81620
fault     14619
attack     3500
Name: count, dtype: int64

PLC2 rows by class:
label
normal    81616
fault     14626
attack     4839
Name: count, dtype: int64

In [95]:
def chronological_split(frame, test_fraction=0.30):
    train_parts = []
    test_parts = []

    for _, group in frame.groupby("label", sort=False):
        group = group.sort_values("time").reset_index(drop=True)
        split_index = int(len(group) * (1 - test_fraction))

        train_parts.append(group.iloc[:split_index])
        test_parts.append(group.iloc[split_index:])

    train = pd.concat(train_parts).sort_values("time").reset_index(drop=True)
    test = pd.concat(test_parts).sort_values("time").reset_index(drop=True)

    return train, test

plc1_train, plc1_test = chronological_split(plc1_model_data)
plc2_train, plc2_test = chronological_split(plc2_model_data)

plc1_features = [
    "loop_latency",
    "logic_execution_time",
    "wall_interval_seconds",
    "current_loop_delta",
    "tank_input_valve_status",
    "tank_input_valve_mode",
    "tank_level_value",
    "tank_level_min",
    "tank_level_max",
    "tank_output_valve_status",
    "tank_output_valve_mode",
    "tank_output_flow_value",
]

plc2_features = [
    "loop_latency",
    "logic_execution_time",
    "wall_interval_seconds",
    "current_loop_delta",
    "conveyor_belt_engine_status",
    "conveyor_belt_engine_mode",
    "bottle_level_value",
    "bottle_level_max",
    "bottle_distance_to_filler_value",
]

for name, train, test in [
    ("PLC1", plc1_train, plc1_test),
    ("PLC2", plc2_train, plc2_test),
]:
    print(f"\n{name} training rows:")
    print(train["label"].value_counts().sort_index())
    print(f"{name} test rows:")
    print(test["label"].value_counts().sort_index())

PLC1 training rows:
label
attack     2450
fault     10233
normal    57134
Name: count, dtype: int64
PLC1 test rows:
label
attack     1050
fault      4386
normal    24486
Name: count, dtype: int64

PLC2 training rows:
label
attack     3387
fault     10238
normal    57131
Name: count, dtype: int64
PLC2 test rows:
label
attack     1452
fault      4388
normal    24485
Name: count, dtype: int64

##**Random Forest**

In [97]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, balanced_accuracy_score, confusion_matrix
import pandas as pd

def train_and_evaluate(train, test, features, name):
    model = RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )

    model.fit(train[features], train["label"])
    predictions = model.predict(test[features])

    print(f"\n{name} — Balanced accuracy: "
          f"{balanced_accuracy_score(test['label'], predictions):.4f}")
    print("\nClassification report:")
    print(classification_report(test["label"], predictions, digits=4))
    print("Confusion matrix (labels: attack, fault, normal):")
    print(confusion_matrix(
        test["label"],
        predictions,
        labels=["attack", "fault", "normal"]
    ))

    return model

plc1_model = train_and_evaluate(
    plc1_train, plc1_test, plc1_features, "PLC1 Random Forest"
)

plc2_model = train_and_evaluate(
    plc2_train, plc2_test, plc2_features, "PLC2 Random Forest"
)

PLC1 Random Forest — Balanced accuracy: 0.7077

Classification report:
              precision    recall  f1-score   support

      attack     0.7529    0.1248    0.2141      1050
       fault     0.9986    1.0000    0.9993      4386
      normal     0.9640    0.9982    0.9808     24486

    accuracy                         0.9678     29922
   macro avg     0.9052    0.7077    0.7314     29922
weighted avg     0.9617    0.9678    0.9566     29922

Confusion matrix (labels: attack, fault, normal):
[[  131     6   913]
 [    0  4386     0]
 [   43     0 24443]]

PLC2 Random Forest — Balanced accuracy: 0.9526

Classification report:
              precision    recall  f1-score   support

      attack     1.0000    0.8581    0.9236      1452
       fault     0.9697    1.0000    0.9846      4388
      normal     0.9969    0.9997    0.9983     24485

    accuracy                         0.9929     30325
   macro avg     0.9889    0.9526    0.9688     30325
weighted avg     0.9931    0.9929    0.9927     30325

Confusion matrix (labels: attack, fault, normal):
[[ 1246   129    77]
 [    0  4388     0]
 [    0     8 24477]]

In [100]:
for name, model, features in [
    ("PLC1", plc1_model, plc1_features),
    ("PLC2", plc2_model, plc2_features),
]:
    importance = (
        pd.Series(model.feature_importances_, index=features)
        .sort_values(ascending=False)
    )

    print(f"\n{name} — Feature importance")
    display(importance.to_frame("importance"))

PLC1 — Feature importance

                          importance
tank_level_value            0.411820
logic_execution_time        0.139352
wall_interval_seconds       0.129142
tank_level_max              0.119660
tank_level_min              0.103408
loop_latency                0.048819
current_loop_delta          0.020411
tank_input_valve_status     0.012042
tank_output_valve_mode      0.006643
tank_output_valve_status    0.004371
tank_output_flow_value      0.004333
tank_input_valve_mode       0.000000

PLC2 — Feature importance

                                 importance
conveyor_belt_engine_mode          0.384892
logic_execution_time               0.160043
conveyor_belt_engine_status        0.118261
wall_interval_seconds              0.082042
bottle_level_value                 0.080172
bottle_distance_to_filler_value    0.069109
bottle_level_max                   0.066978
loop_latency                       0.029020
current_loop_delta                 0.009483

In [99]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, balanced_accuracy_score

for attack_weight in [2, 5, 10]:
    model = RandomForestClassifier(
        n_estimators=300,
        class_weight={
            "normal": 1,
            "fault": 1,
            "attack": attack_weight
        },
        random_state=42,
        n_jobs=-1
    )

    model.fit(plc1_train[plc1_features], plc1_train["label"])
    predictions = model.predict(plc1_test[plc1_features])

    print(f"\nAttack weight = {attack_weight}")
    print("Balanced accuracy:",
          round(balanced_accuracy_score(plc1_test["label"], predictions), 4))
    print(classification_report(
        plc1_test["label"],
        predictions,
        labels=["attack", "fault", "normal"],
        digits=4,
        zero_division=0
    ))

Attack weight = 2
Balanced accuracy: 0.7111
              precision    recall  f1-score   support

      attack     0.7396    0.1352    0.2287      1050
       fault     0.9986    1.0000    0.9993      4386
      normal     0.9644    0.9980    0.9809     24486

    accuracy                         0.9680     29922
   macro avg     0.9009    0.7111    0.7363     29922
weighted avg     0.9615    0.9680    0.9572     29922


Attack weight = 5
Balanced accuracy: 0.7094
              precision    recall  f1-score   support

      attack     0.4896    0.1343    0.2108      1050
       fault     0.9986    1.0000    0.9993      4386
      normal     0.9642    0.9940    0.9789     24486

    accuracy                         0.9647     29922
   macro avg     0.8175    0.7094    0.7297     29922
weighted avg     0.9526    0.9647    0.9549     29922


Attack weight = 10
Balanced accuracy: 0.7077
              precision    recall  f1-score   support

      attack     0.5000    0.1286    0.2045      1050
       fault     0.9986    1.0000    0.9993      4386
      normal     0.9640    0.9945    0.9790     24486

    accuracy                         0.9649     29922
   macro avg     0.8209    0.7077    0.7276     29922
weighted avg     0.9528    0.9649    0.9548     29922

##XGBoost

In [101]:
%pip -q install xgboost

In [102]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, balanced_accuracy_score, confusion_matrix

label_order = ["attack", "fault", "normal"]
encoder = LabelEncoder().fit(label_order)

def train_xgboost(train, test, features, name):
    y_train = encoder.transform(train["label"])
    y_test = encoder.transform(test["label"])

    model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="multi:softprob",
        num_class=3,
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1
    )

    model.fit(train[features], y_train)
    predictions = model.predict(test[features])

    print(f"\n{name} — Balanced accuracy: "
          f"{balanced_accuracy_score(y_test, predictions):.4f}")
    print(classification_report(
        y_test,
        predictions,
        labels=[0, 1, 2],
        target_names=label_order,
        digits=4,
        zero_division=0
    ))
    print("Confusion matrix (attack, fault, normal):")
    print(confusion_matrix(y_test, predictions, labels=[0, 1, 2]))

    return model

plc1_xgb = train_xgboost(
    plc1_train, plc1_test, plc1_features, "PLC1 XGBoost"
)

plc2_xgb = train_xgboost(
    plc2_train, plc2_test, plc2_features, "PLC2 XGBoost"
)

PLC1 XGBoost — Balanced accuracy: 0.7108
              precision    recall  f1-score   support

      attack     0.5926    0.1371    0.2227      1050
       fault     0.9964    1.0000    0.9982      4386
      normal     0.9642    0.9953    0.9795     24486

    accuracy                         0.9659     29922
   macro avg     0.8511    0.7108    0.7335     29922
weighted avg     0.9559    0.9659    0.9557     29922

Confusion matrix (attack, fault, normal):
[[  144     1   905]
 [    0  4386     0]
 [   99    15 24372]]

PLC2 XGBoost — Balanced accuracy: 0.9373
              precision    recall  f1-score   support

      attack     1.0000    0.8127    0.8967      1452
       fault     0.9498    1.0000    0.9742      4388
      normal     0.9976    0.9993    0.9984     24485

    accuracy                         0.9904     30325
   macro avg     0.9825    0.9373    0.9565     30325
weighted avg     0.9908    0.9904    0.9901     30325

Confusion matrix (attack, fault, normal):
[[ 1180   214    58]
 [    0  4388     0]
 [    0    18 24467]]